package com.java1234.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-25T13:58:38.370+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.java1234.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoles", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoles")
    @WebMethod
    @ResponseWrapper(localName = "getRolesResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRolesResponse")
    public com.java1234.webservice.MyRoleArray getRoles();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.Say")
    @WebMethod
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.SayResponse")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleByUid", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoleByUid")
    @WebMethod
    @ResponseWrapper(localName = "getRoleByUidResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.GetRoleByUidResponse")
    public java.util.List<com.java1234.webservice.Role> getRoleByUid(
        @WebParam(name = "arg0", targetNamespace = "")
        com.java1234.webservice.User arg0
    );
}
